### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by wanghangege** [yuantn/MI-AOD#10]
Traceback (most recent call last):
  File "./tools/train.py", line 15, in <module>
    from mmdet import __version__
  File "/media/ubun/CC7251E47251D3B4/yoloseries/miaodxray/MI-AOD/mmdet/__init__.py", line 25, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.3.1 is used but incompatible. Please install mmcv>=1.0.5, <=1.0.5.
Traceback (most recent call last):
  File "/home/ubun/anaconda3/envs/pytorch12/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubun/anaconda3/envs/pytorch12/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubun/anaconda3/envs/pytorch12/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/ubun/anaconda3/envs/pytorch12/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/ubun/anaconda3/envs/pytorch12/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubun/anaconda3/envs/pytorch12/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/MIAOD.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
Killing subprocess 41043

**Comment by wanghangege** [comment]
subprocess.CalledProcessError: Command '['/home/ubun/anaconda3/envs/miaod/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/MIAOD.py', '--launcher', 'pytorch']' died with <Signals.SIGSEGV: 11>.

**Comment by yuantn** [comment]
Please see the Line 6 in your log: "AssertionError: MMCV==1.3.1 is used but incompatible. Please install mmcv>=1.0.5, <=1.0.5."
