### ISSUE TITLE
missing 1 required positional argument: 'x'

### ISSUE THREAD

**Issue by kevinchow1993** [yuantn/MI-AOD#5]
encounter this error when I run ```python -m torch.distributed.launch --nproc_per_node=1 tools/train.py configs/MIAOD.py```

```bash
2021-04-15 16:49:08,902 - mmdet - INFO - load model from: torchvision://resnet50
2021-04-15 16:49:09,276 - mmdet - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

fatal: Not a git repository (or any of the parent directories): .git
2021-04-15 16:49:14,869 - mmdet - INFO - Start running, host: z00495072@poweredge-server-01, work_dir: /home/z00495072/Projects/MI-AOD-master/work_dirs/MI-AOD/20210415_164906
2021-04-15 16:49:14,869 - mmdet - INFO - workflow: [('train', 1)], max: 3 epochs
Traceback (most recent call last):
  File "tools/train.py", line 267, in <module>
    main()
  File "tools/train.py", line 180, in main
    distributed=distributed, validate=(not args.no_validate), timestamp=timestamp, meta=meta)
  File "/home/z00495072/Projects/MI-AOD-master/mmdet/apis/train.py", line 120, in train_detector
    runner.run(data_loaders_L, cfg.workflow, cfg.total_epochs)
  File "/home/z00495072/anaconda3/envs/miaod/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/z00495072/anaconda3/envs/miaod/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in train
    **kwargs)
  File "/home/z00495072/anaconda3/envs/miaod/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 31, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/z00495072/Projects/MI-AOD-master/mmdet/models/detectors/base.py", line 228, in train_step
    losses = self(**data)
  File "/home/z00495072/anaconda3/envs/miaod/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/z00495072/Projects/MI-AOD-master/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
TypeError: forward() missing 1 required positional argument: 'x'
Traceback (most recent call last):
  File "/home/z00495072/anaconda3/envs/miaod/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/z00495072/anaconda3/envs/miaod/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/z00495072/anaconda3/envs/miaod/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/z00495072/anaconda3/envs/miaod/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/z00495072/anaconda3/envs/miaod/bin/python', '-u', 'tools/train.py', '--local_rank=0', 'configs/MIAOD.py']' returned non-zero exit status 1.

```

**Comment by yuantn** [comment]
> encounter this error when I run `python -m torch.distributed.launch --nproc_per_node=1 tools/train.py configs/MIAOD.py`
> 
> ```shell
> 2021-04-15 16:49:08,902 - mmdet - INFO - load model from: torchvision://resnet50
> 2021-04-15 16:49:09,276 - mmdet - WARNING - The model and loaded state dict do not match exactly
> 
> unexpected key in source state_dict: fc.weight, fc.bias
> 
> fatal: Not a git repository (or any of the parent directories): .git
> 2021-04-15 16:49:14,869 - mmdet - INFO - Start running, host: z00495072@poweredge-server-01, work_dir: /home/z00495072/Projects/MI-AOD-master/work_dirs/MI-AOD/20210415_164906
> 2021-04-15 16:49:14,869 - mmdet - INFO - workflow: [('train', 1)], max: 3 epochs
> Traceback (most recent call last):
>   File "tools/train.py", line 267, in <module>
>     main()
>   File "tools/train.py", line 180, in main
>     distributed=distributed, validate=(not args.no_validate), timestamp=timestamp, meta=meta)
>   File "/home/z00495072/Projects/MI-AOD-master/mmdet/apis/train.py", line 120, in train_detector
>     runner.run(data_loaders_L, cfg.workflow, cfg.total_epochs)
>   File "/home/z00495072/anaconda3/envs/miaod/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/home/z00495072/anaconda3/envs/miaod/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in train
>     **kwargs)
>   File "/home/z00495072/anaconda3/envs/miaod/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 31, in train_step
>     return self.module.train_step(*inputs[0], **kwargs[0])
>   File "/home/z00495072/Projects/MI-AOD-master/mmdet/models/detectors/base.py", line 228, in train_step
>     losses = self(**data)
>   File "/home/z00495072/anaconda3/envs/miaod/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/z00495072/Projects/MI-AOD-master/mmdet/core/fp16/decorators.py", line 51, in new_func
>     return old_func(*args, **kwargs)
> TypeError: forward() missing 1 required positional argument: 'x'
> Traceback (most recent call last):
>   File "/home/z00495072/anaconda3/envs/miaod/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/z00495072/anaconda3/envs/miaod/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/z00495072/anaconda3/envs/miaod/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
>     main()
>   File "/home/z00495072/anaconda3/envs/miaod/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
>     cmd=cmd)
> subprocess.CalledProcessError: Command '['/home/z00495072/anaconda3/envs/miaod/bin/python', '-u', 'tools/train.py', '--local_rank=0', 'configs/MIAOD.py']' returned non-zero exit status 1.
> ```

Please refer to [Modification in the mmcv Package](https://github.com/yuantn/MI-AOD#modification-in-the-mmcv-package). That is, you are supposed to copy the “epoch_base_runner.py” provided in this repository to the mmcv directory (as described in the README.md).

**Comment by kevinchow1993** [comment]
thx! problem solved!
