### ISSUE TITLE
你好，我在运行./script.sh 0 时遇到了问题

### ISSUE THREAD

**Issue by wuliacbd** [yuantn/MI-AOD#66]
你好，我在运行./script.sh 0 时遇到了这个问题

20220417_153805
2022-04-17 15:38:11,510 - mmdet - INFO - workflow: [('train', 1)], max: 3 epochs
Traceback (most recent call last):
  File "tools/train.py", line 257, in <module>
    main()
  File "tools/train.py", line 170, in main
    distributed=distributed, validate=(not args.no_validate), timestamp=timestamp, meta=meta)
  File "/home/liugh/MI-AOD-master/mmdet/apis/train.py", line 120, in train_detector
    runner.run(data_loaders_L, cfg.workflow, cfg.total_epochs)
  File "/home/liugh/.conda/envs/miaod/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 121, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/liugh/.conda/envs/miaod/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 31, in train
    outputs = self.model.train_step(data_batch, self.optimizer,**kwargs)
  File "/home/liugh/.conda/envs/miaod/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 31, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/liugh/MI-AOD-master/mmdet/models/detectors/base.py", line 228, in train_step
    losses = self(**data)
  File "/home/liugh/.conda/envs/miaod/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/liugh/MI-AOD-master/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
TypeError: forward() missing 1 required positional argument: 'x'

**Comment by wuliacbd** [comment]
这个问题已经解决了，不好意思打扰了
